stages:
- name: Build
  steps:
  - runScriptConfig:
      image: oraclelinux:7-slim
      shellScript: ssh 
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ledivan:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
